# @file
# Drupal-related tasks: database dump etc.

- name: Configure.
  with_first_found:
    - "../../../vars/drupal.yml"
  include_vars: "{{ item }}"

- name: Check if database dump exists.
  stat: path="/var/dumps/{{ database.name }}.sql.gz"
  register: dump

- name: Import database dump.
  mysql_db: >
    name={{ database.name }} state=import
    target='/var/dumps/{{ database.name }}.sql.gz'
  when: dump.stat.exists

- name: Move database dump aside.
  command: >
    mv /var/dumps/{{ database.name }}.sql.gz
    /var/dumps/{{ database.name }}.sql.gz.imported
  when: dump.stat.exists

- name: Ensure files folder contents owned by www-data.
  file: >
    dest={{ codebase.folders.files }} owner=www-data
    group=www-data mode=0775 recurse=yes

- name: Ensure files in the files folder locked down to r-xr-xr--.
  command: find "{{ codebase.folders.files }}" -type f -exec chmod 0644 {} \;

- name: Add a local-settings.php file suitable for Drupal {{ codebase.drupal_version }}.x.
  template:
    src: templates/drupal-{{ codebase.drupal_version }}-local-settings.php.j2
    dest: /var/www/web/sites/default/local-settings.php
    owner: root
    group: root
    mode: 0644
  with_items:
    - '{{ database }}'

- name: Install composer.
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
